# NO-OP placeholder that always passes for other paths
# This is here so that we're able to set the status check as required

name: Chromatic Void
on:
  pull_request:
    paths-ignore:
      - '.github/workflows/verify_chromatic.yml'
      - '.storybook/**'
      - 'packages/ui/src/**'
      - '**/*.stories.tsx'

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest

    name: Chromatic
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - run: echo NOOP
